name: Publish Package to npmjs
on:
  push:
    branches: main , master
jobs:
  publish:
    runs-on: ubuntu-latest # Must run on GitHub-hosted runners
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g corepack && corepack enable corepack use pnpm@10
      - run: pnpm install && pnpm build
      - run: pnpm config set npmAuthToken '${{ secrets.NPM_TOKEN }}'
      - run: yarn publish --provenance --tolerate-republish
      
