name: Publish Package to npmjs
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest # Must run on GitHub-hosted runners
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g corepack && corepack enable
      - run: yarn && yarn build
      - run: yarn config set npmAuthToken '${{ secrets.NPM_TOKEN }}'
      - run: yarn publish --provenance --tolerate-republish
      
